### ISSUE TITLE
Doesn't Seem to Work on Nextcloud 23 on Local Storage / Nextcloud 24 on External Storage

### ISSUE THREAD

**Issue by janusn** [Inveniem/nextcloud-files-excludedirs#2]
**Synopsis:**

Folders from external storage acquired with local method is not excluded. I am not sure whether the non-external folders since I use it mainly on external storage.

**Procedures performed:**
- files_excludedirs was chown'ed and chmod'ed
- app installed and enabled
- Settings (sorry for the ugly syntax. It is required to run inside the container)
`# sudo -u abc -s /bin/bash -c "php7 /config/www/nextcloud/occ config:app:set files_excludedirs exclude --value '[\"@eaDir\",\"#snapshot\",\".*\"]'"`
`Config value exclude for app files_excludedirs set to ["@eaDir","#snapshot",".*"]`
- clean up the table oc_filecache with
`DELETE FROM oc_filecache WHERE oc_filecache.path = '@eaDir';`
`DELETE FROM oc_filecache WHERE oc_filecache.path = '#snapshot';`
`DELETE FROM oc_filecache WHERE oc_filecache.path LIKE '._%';`

**Expected result:**

No folder with the name "@eaDir" or "#snapshot" shows up.

**Actual result:**

Folders with the name "@eaDir" or "#snapshot" are still visible.

**Environment:**
- files_excludedirs [version 1.0.0.beta](https://github.com/Inveniem/nextcloud-files-excludedirs/releases/tag/v1.0.0-beta)
- Hardware: Synology DS918+ and DX517, 16 GB RAM
- Host: Synology DSM 7.1-42661 Update 4
- Nextcloud: [linuxserver/nextcloud 24.0.5](https://registry.hub.docker.com/layers/linuxserver/nextcloud/24.0.5/images/sha256-5a425e6d43c07f51bc8dca86b7b4f50b80d4e3a1f8f267f5081336229516b2c2?context=explore)
- Database: [linuxserver/mariadb 10.5.17](https://registry.hub.docker.com/layers/linuxserver/mariadb/10.5.17/images/sha256-e7b4b37643faa11f5470f0987b0a43c52493683a0120c9d0bd7476166d2b76a1?context=explore)

**Comment by wonx** [comment]
My previous test that I mentioned in https://github.com/nextcloud/server/issues/26651#issuecomment-1243039588 was also applied to an external storage and didn't work, the folders were scanned to the database.

**Comment by GuyPaddock** [comment]
@wonx Thanks for filing this! I'll do more testing on NC v24. We are _also_ using it almost exclusively with external storage and it's working for us in v23, so I'll have to see if I can identify what's different.

**Comment by GuyPaddock** [comment]
@wonx The work item for this finally came up in my work queue so I could take another look at this. I can confirm that this does not appear to work in NC 24 even with local storage. I am looking to see what changed between 23 and 24 here.

**Comment by GuyPaddock** [comment]
I'm able to reproduce this issue on _local storage_ in NC 23, even though it was working for me with SMB-mounted external storage in NC 23 previously.

**Comment by GuyPaddock** [comment]
@janusn @wonx Can you try this new release? https://github.com/Inveniem/nextcloud-files-excludedirs/releases/tag/v1.0.1-beta

Again, this will only affect _new_ files not files that NC already knows about, so just bear that in mind.

**Comment by wonx** [comment]
I did a quick test and seems to ignore the specified folder, so, so far so good! I'll write back if I find any issues.

**Comment by janusn** [comment]
@GuyPaddock
I would love to help.
A question though. In case of a problem arise, could I uninstall it simply by removing the app directory to restore Nextcloud?

Thanks in advance.

**Comment by GuyPaddock** [comment]
@janusn I would recommend disabling it through the `occ app:disable` CLI command first, if you can.

**Comment by janusn** [comment]
@GuyPaddock 

Sorry for the late reply. My NAS was a bit funky and it took me quite a while to get it back to work.

I can say the v.1.0.1 beta does not crash my NextCloud setup. I can log on it without an error. I cannot confirm the functionality yet as I am still cleaning up the filecache table. It takes much longer than I expect. I will report back once I have completed.

Thanks for your effort.

**Comment by wonx** [comment]
From my part, it seems to be working just fine. The complete directory scan, which used to take around 45-50 minutes, lowered to less than 20 minutes after excluded a folder with tens of thousands of subfolders, so I couldn't be happier.

**Comment by janusn** [comment]
@GuyPaddock 

Sorry for the long waiting. I have reinstalled every thing related nextcloud including swag, redis, mariadb, duckdns...

I am happy to report that after 3 days of running, the app seems to work well. Thank you.

...
A little more question though. How do I exclude any file or directory starting with a dot? I have tried "/.\*" , ".\*" and "\*/.\*" but any one of them prevented the root of docker volumes in external storage from working. strangely, the subdirectories worked fine.

for example:
with a docker-compose.yaml

```
version: "2.1"
services:
  nextcloud:
    image: linuxserver/nextcloud:latest
    container_name: nextcloud
    volumes:
      - /volume2/docker/nextcloud/config:/config
      - /volume2/nextcloud/data:/data
      - /volume2/Media:/mnt/media
    restart: unless-stopped
```
and settings of
`$ php /config/www/nextcloud/occ config:app:set files_excludedirs exclude --value '["/.*"]'`
The occ is located there on the container linuxserver/nextcloud image.

An external storage to `/mnt/media` via local method throw an error and cannot be opened on nextcloud.
But an external storage to `/mnt/media/bin` via local method works totally fine.

**Comment by GuyPaddock** [comment]
@janusn Wonderful!

Can you open a separate issue for your question? I'm actually not 100% sure of the answer since I did not write the original globbing support; I just fixed it up for this version. But if we have a separate issue for it someone else may be able to chime in before I find out :)

**Comment by janusn** [comment]
@GuyPaddock I have created #3 as requested.

Furthermore, I filed another bug #4 as well.

Thanks a ton for this wonderful app!

**Comment by rightsaidfred99** [comment]
I can confirm this bug exists still with 24. 
<img width="827" alt="Screenshot 2023-01-11 at 16 53 38" src="https://user-images.githubusercontent.com/74799127/211728309-45bdf58f-9a0a-4277-8d54-ce52cccdf3ce.png">
<img width="1232" alt="Screenshot 2023-01-11 at 16 53 49" src="https://user-images.githubusercontent.com/74799127/211728321-e92291d7-806c-4d03-953f-65e351df5359.png">

**Comment by rightsaidfred99** [comment]
On new folders, @eaDir pops up 100% of the time.
